<a href="https://colab.research.google.com/github/camilanicola/projetos_alura_classificacao/blob/main/classificacao_por_tras_dos_panos_alura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Customer-Churn.csv to Customer-Churn.csv
User uploaded file "Customer-Churn.csv" with length 807578 bytes


In [4]:
dados=pd.read_csv('/content/Customer-Churn.csv')

In [5]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [6]:
dados.shape

(7043, 18)

In [7]:
trad_dic={'Sim':1,'Nao':0}

dados_modificados=dados[['Conjuge','Dependentes','TelefoneFixo','PagamentoOnline','Churn']].replace(trad_dic)
dados_modificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [8]:
##outra forma de modificar os dados
dummie_dados=pd.get_dummies(dados.drop(['Conjuge','Dependentes','TelefoneFixo','PagamentoOnline','Churn'],axis=1))

dados_final=pd.concat([dados_modificados,dummie_dados],axis=1)

In [9]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                        False   
1               34        56.95                         True   
2                2        53.85                         True   
3               45        42.30                        False   
4                2        70.70                         True   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                          True  ...                   True   
1                                         False  ...                   True   
2                                         False  ...                   True   
3                                          True  ...                   True   
4                                         False  ...                   True   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                   False                  False   
1                                   False                  False   
2                                   False                  False   
3                                   False                  False   
4                                   False                  False   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                    False                        True                 False   
1                    False                       False                  True   
2                    False                        True                 False   
3                    False                       False                  True   
4                    False                        True                 False   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                             False                            True   
1                             False                           False   
2                             False                           False   
3                             False                           False   
4                             False                            True   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                         False                           False  
1                          True                           False  
2                          True                           False  
3                         False                            True  
4                         False                           False  

[5 rows x 39 columns]

In [10]:
dados_final.shape

(7043, 39)

# *Método baseado na proximidade (KNN)*#


In [11]:
##calculo da probabilidade de um cliente deixar a empresa
x=dados_final.drop('Churn',axis=1)
y=dados_final['Churn']

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
norm=StandardScaler()
x_normalizado=norm.fit_transform(x)
x_normalizado

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

In [14]:
Xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [15]:
Xmaria_normalizado=norm.transform(pd.DataFrame(Xmaria, columns = x.columns))
Xmaria_normalizado

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

In [16]:
import numpy as np

In [17]:
a=Xmaria_normalizado

In [18]:
b=x_normalizado[0]

In [19]:
dist_euclidiana=np.sqrt(np.sum(np.square(a-b)))

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_treino,X_teste,y_treino,y_teste=train_test_split(x_normalizado,y,test_size=0.3,random_state=42)

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
knn=KNeighborsClassifier(metric='euclidean')

In [24]:
knn.fit(X_treino,y_treino)

KNeighborsClassifier(metric='euclidean')

In [25]:
predito_knn=knn.predict(X_teste)
predito_knn

array([1, 0, 0, ..., 0, 1, 0])

# *Método Probabilístico (Naive Bayes)*

In [26]:
np.median(X_treino)

-0.5259273725834717

In [27]:
from sklearn.naive_bayes import BernoulliNB

In [28]:
bnb=BernoulliNB(binarize=0.52)

In [29]:
bnb.fit(X_treino,y_treino)

BernoulliNB(binarize=0.52)

In [30]:
predito_bnb=bnb.predict(X_teste)
predito_bnb

array([1, 0, 0, ..., 0, 1, 1])

# *Método simbólico (Árvore de decisão)*

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
dtc=DecisionTreeClassifier(criterion='entropy', random_state=42)

In [33]:
dtc.fit(X_treino,y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [34]:
dtc.feature_importances_

array([0.02676622, 0.02191232, 0.00123207, 0.02687951, 0.02167519,
       0.19624992, 0.30586553, 0.01042559, 0.00114239, 0.00740101,
       0.01813303, 0.00330662, 0.        , 0.03283784, 0.        ,
       0.00502891, 0.01208467, 0.        , 0.0096151 , 0.00899309,
       0.        , 0.00864563, 0.00732592, 0.        , 0.00621712,
       0.01073686, 0.        , 0.00679059, 0.00687678, 0.        ,
       0.01151522, 0.01377271, 0.15446229, 0.        , 0.0158334 ,
       0.02254153, 0.01110261, 0.01463034])

In [35]:
predito_arv_dec=dtc.predict(X_teste)

In [36]:
predito_arv_dec

array([1, 0, 0, ..., 0, 0, 0])

# *Validação dos modelos (Matriz Confusão)*

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score

In [38]:
print(confusion_matrix(y_teste,predito_knn))

[[1303  236]
 [ 301  273]]


In [42]:
print(accuracy_score(y_teste,predito_knn))

0.7458589682915286


In [46]:
print(precision_score(y_teste,predito_knn))

0.5363457760314342


In [39]:
print(confusion_matrix(y_teste,predito_bnb))

[[1062  477]
 [  91  483]]


In [43]:
print(accuracy_score(y_teste,predito_bnb))

0.7311878845243729


In [47]:
print(precision_score(y_teste,predito_bnb))

0.503125


In [40]:
print(confusion_matrix(y_teste,predito_arv_dec))

[[1257  282]
 [ 280  294]]


In [44]:
print(accuracy_score(y_teste,predito_arv_dec))

0.7340274491244676


In [48]:
print(precision_score(y_teste,predito_arv_dec))

0.5104166666666666
